### ISSUE TITLE
hash.h: No such file or directory

### ISSUE THREAD

**Issue by jlz3008** [SparkiDev/random#1]
$  make
gcc -c -O3 -m64 -Wall -Werror -Wextra -DCPU_X86_64 -DCC_GCC -DOS_LINUX -Iinclude -I../hash/include -o random.o src/random.c
In file included from src/random_lcl.h:24:0,
                 from src/random.c:26:
src/random_hash.h:28:18: fatal error: hash.h: No such file or directory
 #include "hash.h"
                  ^
compilation terminated.
make: *** [random.o] Error 1

**Comment by SparkiDev** [comment]
Updated README.md, the 'Build' section, to explain the requirement for hash repository.
